---
- hosts: web2
  vars:
    docker_group: docker
    ssh_remote_user: eltomas
  become: yes
  become_method: sudo
  tasks:
  # sudo apt-get install *
  - name: Install docker packages
    apt:
      name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg2
      - software-properties-common
      state: present
      update_cache: yes
  # curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - name: Add Docker's official GPG key
    apt_key:
      url: https://download.docker.com/linux/debian/gpg
      state: present
    tags:
    - docker
    # sudo apt-key fingerprint 0EBFCD88
  - name: Verify that we have the key with the fingerprint
    apt_key:
      id: 0EBFCD88
      state: present
    tags:
    - docker
  # sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian stretch stable"
  - name: Set up the stable repository
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/debian stretch stable
      state: present
      update_cache: yes
    tags:
    - docker
  # sudo apt-get update
  - name: Update apt packages
    apt:
      update_cache: yes
    tags:
    - docker
  # sudo apt-get install docker-ce
  - name: Install docker
    apt:
      name: docker-ce
      state: present
      update_cache: yes
    tags:
    - docker
  # sudo groupadd docker
  - name: Create "docker" group
    group:
      name: "{{ docker_group }}"
      state: present
    tags:
    - docker
  # sudo usermod -aG docker eltomas
  - name: Add remote "eltomas" user to "docker" group
    user:
      name: "{{ ssh_remote_user }}"
      group: "{{ docker_group }}"
      append: yes
    tags:
    - docker
  # sudo apt-get install docker-compose 1.23.1
  - name: Download Docker-CE
    shell: curl -L "https://github.com/docker/compose/releases/download/1.23.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  - name: Chmod +x
    shell: sudo chmod +x /usr/local/bin/docker-compose
  - name: copy docker-compose.yml
    copy:
      src: ./docker-compose.yml
      dest: ./docker-compose.yml
  - name: run docker-compose
    environment:
      BUILD_TIMESTAMP: "{{ lookup('env', 'BUILD_TIMESTAMP') }}"
    docker_service:
      project_src: .
      state: present
      restarted: yes